---
title: "Modeling Script"
output: github_document
date: "Last Update: July 24, 2024"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Package Loading

```{r}
library(tidyverse)
library(forcats)
library(lazyeval)
library(ggpubr)
library(ggridges)
library(RColorBrewer)
```

# Data Loading

```{r}
lca_data <- read.csv("/Users/kenjinchang/github/multimodal-dining-study/data/parent-data/lca-factors.csv")
```

```{r}
recipe_modeling <- read.csv("/Users/kenjinchang/github/multimodal-dining-study/data/parent-data/recipe-modeling.csv",na.strings=c("","NA"))
```


# Data Cleaning

```{r}
lca_data
```

```{r}
recipe_modeling
```

```{r}
footprint_calculations <- left_join(recipe_modeling,lca_data) %>%
  select(station,recipe,ingredient,listed_quantity,weight_oz,matched_ingredient,matched_ingredient_source,mean_kg_co2e_per_kg,mean_l_h2o_blue_per_kg,mean_l_h2o_green_per_kg) %>%
  filter(!is.na(weight_oz)) %>%
  mutate(weight_kg=weight_oz*0.028349523) %>%
  mutate(kg_co2e=weight_kg*mean_kg_co2e_per_kg) %>%
  mutate(l_h2o_blue=weight_kg*mean_l_h2o_blue_per_kg) %>%
  mutate(l_h2o_green=weight_kg*mean_l_h2o_green_per_kg) %>%
  mutate(l_h2o_total=l_h2o_blue+l_h2o_green)
```

```{r}
footprint_calculations 
```


```{r}
item_kg_co2e <- footprint_calculations %>% group_by(recipe) %>%
  summarise(sum(kg_co2e))
item_kg_co2e
```

```{r}
write.csv(item_kg_co2e,"~/github/multimodal-dining-study/data/output/item-kg-co2e.csv")
```


```{r}
item_l_h2o_blue <- footprint_calculations %>% group_by(recipe) %>%
  summarise(sum(l_h2o_blue))
item_l_h2o_blue
```

```{r}
write.csv(item_l_h2o_blue,"~/github/multimodal-dining-study/data/output/item-l-h2o-blue.csv")
```




